# Generated by Django 3.2.7 on 2021-10-24 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('indications', models.TextField()),
                ('contraindications', models.TextField()),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'Available'), ('U', 'Unavailable')], max_length=1)),
                ('types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmAPI.types', verbose_name='Class')),
            ],
        ),
    ]
